name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables on Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          curl -X PATCH "https://api.netlify.com/api/v1/sites/${{ secrets.SIDE_ID }}" \
          -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
          -H "Content-Type: application/json" \
          --data '{
            "build_settings": {
              "env": {
                "NEXT_PUBLIC_FIREBASE_APIKEY": "'${{ secrets.NEXT_PUBLIC_FIREBASE_APIKEY }}'",
                "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN": "'${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}'",
                "NEXT_PUBLIC_FIREBASE_PROJECT_ID": "'${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}'",
                "NEXT_PUBLIC_FIREBASE_STORAGE": "'${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE }}'",
                "NEXT_PUBLIC_FIREBASE_MESSAGING": "'${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING }}'",
                "NEXT_PUBLIC_FIREBASE_APP_ID": "'${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}'",
                "NEXT_PUBLIC_FIREBASE_MEASUREMENT": "'${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT }}'"
              }
            }
          }'

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: ./out # Cambia esto al directorio generado por tu build
          production-deploy: true
          deploy-message: 'Automated deployment'
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.SIDE_ID }}
