name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_FIREBASE_APIKEY=${{ secrets.NEXT_PUBLIC_FIREBASE_APIKEY }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_STORAGE=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_MEASUREMENT=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT }}" >> .env

      - name: Verify environment variables
        run: |
          echo ${{ secrets.NEXT_PUBLIC_FIREBASE_APIKEY }}
          echo ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          echo ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          echo ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE }}
          echo ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING }}
          echo ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          echo ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT }}
          echo ${{ secrets.NETLIFY_AUTH_TOKEN }}
          echo ${{ secrets.SIDE_ID }}

      - name: Set environment variables on Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          curl -X PATCH "https://api.netlify.com/api/v1/sites/${{ secrets.SIDE_ID }}" \
          -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
          -H "Content-Type: application/json" \
          --data '{
            "build_settings": {
              "env": {
                "NEXT_PUBLIC_FIREBASE_APIKEY": "'${{ secrets.NEXT_PUBLIC_FIREBASE_APIKEY }}'",
                "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN": "'${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}'",
                "NEXT_PUBLIC_FIREBASE_PROJECT_ID": "'${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}'",
                "NEXT_PUBLIC_FIREBASE_STORAGE": "'${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE }}'",
                "NEXT_PUBLIC_FIREBASE_MESSAGING": "'${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING }}'",
                "NEXT_PUBLIC_FIREBASE_APP_ID": "'${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}'",
                "NEXT_PUBLIC_FIREBASE_MEASUREMENT": "'${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT }}'"
              }
            }
          }'

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: ./out
          production-deploy: true
          deploy-message: 'Automated deployment'
